# Generated by Django 5.1.3 on 2025-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("resume", models.FileField(upload_to="resume")),
            ],
        ),
    ]
