# Generated by Django 5.1.3 on 2025-03-17 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="GeeksModel",
        ),
        migrations.AddField(
            model_name="resume",
            name="email_address",
            field=models.CharField(default="example@example.com", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
