# Generated by Django 5.1.3 on 2025-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_jobdescription_delete_geeksmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdescription",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="jobdescription",
            name="title",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="name",
        ),
    ]
