# Generated by Django 5.1.3 on 2025-04-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_jobdescription_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resume")),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="JobDescription",
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
    ]
