services:
  db:
    image: postgres:16
    container_name: resumehint-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resumehint
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py migrate
    env_file: ".env"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
