services:
  db:
    image: postgres:16
    container_name: resumehint-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resumehint
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    build:
      context: ./apps/api
      dockerfile: Dockerfile-dev
    command: python manage.py migrate
    environment:
      - DB_NAME=resumehint
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    networks:
      - app-network
    environment:
      - DB_NAME=resumehint
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432

    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

networks:
  app-network:
    driver: bridge

volumes:
  db-data: